export default {
    // --------- PIQUE --------- //
    AsDePique:   require('./AsDePique.png'),
    DeuxDePique: require('./DeuxDePique.png'),
    TroisDePique: require('./TroisDePique.png'),
    QuatreDePique: require('./QuatreDePique.png'),
    CinqDePique: require('./CinqDePique.png'),
    SixDePique: require('./SixDePique.png'),
    SeptDePique: require('./SeptDePique.png'),
    HuitDePique: require('./HuitDePique.png'),
    NeufDePique: require('./NeufDePique.png'),
    DixDePique: require('./DixDePique.png'),
    ValetDePique: require('./ValetDePique.png'),
    DameDePique: require('./DameDePique.png'),
    RoiDePique: require('./RoiDePique.png'),

    // --------- TREFLE -------- //
    AsDeTrefle:   require('./AsDeTrefle.png'),
    DeuxDeTrefle: require('./DeuxDeTrefle.png'),
    TroisDeTrefle: require('./TroisDeTrefle.png'),
    QuatreDeTrefle: require('./QuatreDeTrefle.png'),
    CinqDeTrefle: require('./CinqDeTrefle.png'),
    SixDeTrefle: require('./SixDeTrefle.png'),
    SeptDeTrefle: require('./SeptDeTrefle.png'),
    HuitDeTrefle: require('./HuitDeTrefle.png'),
    NeufDeTrefle: require('./NeufDeTrefle.png'),
    DixDeTrefle: require('./DixDeTrefle.png'),
    ValetDeTrefle: require('./ValetDeTrefle.png'),
    DameDeTrefle: require('./DameDeTrefle.png'),
    RoiDeTrefle: require('./RoiDeTrefle.png'),

    // --------- CARREAU -------- //
    AsDeCarreau:   require('./AsDeCarreau.png'),
    DeuxDeCarreau: require('./DeuxDeCarreau.png'),
    TroisDeCarreau: require('./TroisDeCarreau.png'),
    QuatreDeCarreau: require('./QuatreDeCarreau.png'),
    CinqDeCarreau: require('./CinqDeCarreau.png'),
    SixDeCarreau: require('./SixDeCarreau.png'),
    SeptDeCarreau: require('./SeptDeCarreau.png'),
    HuitDeCarreau: require('./HuitDeCarreau.png'),
    NeufDeCarreau: require('./NeufDeCarreau.png'),
    DixDeCarreau: require('./DixDeCarreau.png'),
    ValetDeCarreau: require('./ValetDeCarreau.png'),
    DameDeCarreau: require('./DameDeCarreau.png'),
    RoiDeCarreau: require('./RoiDeCarreau.png'),

    // --------- COEURS -------- //
    AsDeCoeur:   require('./AsDeCoeur.png'),
    DeuxDeCoeur: require('./DeuxDeCoeur.png'),
    TroisDeCoeur: require('./TroisDeCoeur.png'),
    QuatreDeCoeur: require('./QuatreDeCoeur.png'),
    CinqDeCoeur: require('./CinqDeCoeur.png'),
    SixDeCoeur: require('./SixDeCoeur.png'),
    SeptDeCoeur: require('./SeptDeCoeur.png'),
    HuitDeCoeur: require('./HuitDeCoeur.png'),
    NeufDeCoeur: require('./NeufDeCoeur.png'),
    DixDeCoeur: require('./DixDeCoeur.png'),
    ValetDeCoeur: require('./ValetDeCoeur.png'),
    DameDeCoeur: require('./DameDeCoeur.png'),
    RoiDeCoeur: require('./RoiDeCoeur.png'),
};
