export default {
    // --------- PIQUE --------- //
    AsDePique:   require('./AsDePique.png'),
    DeuxDePique: require('./2DePique.png'),
    TroisDePique: require('./3DePique.png'),
    QuatreDePique: require('./4DePique.png'),
    CinqDePique: require('./5DePique.png'),
    SixDePique: require('./6DePique.png'),
    SeptDePique: require('./7DePique.png'),
    HuitDePique: require('./8DePique.png'),
    NeufDePique: require('./9DePique.png'),
    DixDePique: require('./10DePique.png'),
    ValetDePique: require('./ValetDePique.png'),
    DameDePique: require('./DameDePique.png'),
    RoiDePique: require('./RoiDePique.png'),

    // --------- TREFLE -------- //
    AsDeTrefle:   require('./AsDeTrefle.png'),
    DeuxDeTrefle: require('./2DeTrefle.png'),
    TroisDeTrefle: require('./3DeTrefle.png'),
    QuatreDeTrefle: require('./4DeTrefle.png'),
    CinqDeTrefle: require('./5DeTrefle.png'),
    SixDeTrefle: require('./6DeTrefle.png'),
    SeptDeTrefle: require('./7DeTrefle.png'),
    HuitDeTrefle: require('./8DeTrefle.png'),
    NeufDeTrefle: require('./9DeTrefle.png'),
    DixDeTrefle: require('./10DeTrefle.png'),
    ValetDeTrefle: require('./ValetDeTrefle.png'),
    DameDeTrefle: require('./DameDeTrefle.png'),
    RoiDeTrefle: require('./RoiDeTrefle.png'),

    // --------- CARREAU -------- //
    AsDeCarreau:   require('./AsDeCarreau.png'),
    DeuxDeCarreau: require('./2DeCarreau.png'),
    TroisDeCarreau: require('./3DeCarreau.png'),
    QuatreDeCarreau: require('./4DeCarreau.png'),
    CinqDeCarreau: require('./5DeCarreau.png'),
    SixDeCarreau: require('./6DeCarreau.png'),
    SeptDeCarreau: require('./7DeCarreau.png'),
    HuitDeCarreau: require('./8DeCarreau.png'),
    NeufDeCarreau: require('./9DeCarreau.png'),
    DixDeCarreau: require('./10DeCarreau.png'),
    ValetDeCarreau: require('./ValetDeCarreau.png'),
    DameDeCarreau: require('./DameDeCarreau.png'),
    RoiDeCarreau: require('./RoiDeCarreau.png'),

    // --------- COEURS -------- //
    AsDeCoeur:   require('./AsDeCoeur.png'),
    DeuxDeCoeur: require('./2DeCoeur.png'),
    TroisDeCoeur: require('./2DeCoeur.png'),
    QuatreDeCoeur: require('./2DeCoeur.png'),
    CinqDeCoeur: require('./2DeCoeur.png'),
    SixDeCoeur: require('./2DeCoeur.png'),
    SeptDeCoeur: require('./2DeCoeur.png'),
    HuitDeCoeur: require('./2DeCoeur.png'),
    NeufDeCoeur: require('./2DeCoeur.png'),
    DixDeCoeur: require('./2DeCoeur.png'),
    ValetDeCoeur: require('./2DeCoeur.png'),
    DameDeCoeur: require('./2DeCoeur.png'),
    RoiDeCoeur: require('./2DeCoeur.png'),
};
